### ISSUE TITLE
Device Does Not Show Up

### ISSUE THREAD

**Issue by Mstar456** [mrrfv/linux-android-backup#20]
Hi I have several devices I am trying to recover and neither of them show up in the device list

**Comment by mrrfv** [comment]
What operating system are you running Linux Android Backup on? Did you enable USB debugging on your devices and set them to file transfer mode?

P.S. I haven't tested the script with multiple devices, so you should plug them in to your computer one at a time.

**Comment by Mstar456** [comment]
Windows 10, it was my own fault as i misunderstood the instructions.

I enabled decleoper options as per the guidez but didn't enable USB debugging, I did this but no matter which device I tried it would fail after about a minute of the backup starting with the following error:

Tar error: Unexpected EOF in archive

Or it would just say unexpected error and collapse.

Thanks

**Comment by mrrfv** [comment]
Sounds like an issue with the connection to your device, or an incompatibility between the `tar` binary on your phone and computer. In order to rule out the possibility of the cable being faulty, could you try a different cable, or even enable wireless debugging (if you have some experience with adb)? Also, what are the devices you're trying to recover (model, Android version, manufacturer)?

**Comment by Mstar456** [comment]
Hi,

I'm an entry level cloud engineer, usually stick to windows but I'm foraging into tinkering with Linux and stuff to try and increase my skillset, 
Nowhere near as experienced as you making awesome pieces of kit like you have.

I have a note 9, a note 9, and an s8+, ill change the cable and let you know how it goes, I'll try see if I can figure out the wireless debugging.

Thanks for your help!

**Comment by Mstar456** [comment]
Mate, i wish all devs were like you 🤣 first experience on github. Won't forget. Quite enjoying tinkering. And appreciate the thanks

**Comment by mrrfv** [comment]
#21 has confirmed that this issue is not limited to just your device or cable, but all devices that ship with incompatible versions of tar. I've readded the old and widely compatible method Linux Android Backup used to get data from the device, and all you need to do is choose the `adb` exporting method when the script asks.
