### ISSUE TITLE
Device not show up in script

### ISSUE THREAD

**Issue by sam1946** [mrrfv/linux-android-backup#33]
## Device info

Manufacturer: Samsung Galaxy S5
Android version: 11
Custom ROM/rooted? Rooted and custom rom, lineageOS, Android 11
Model: GT i9505

## System info
Fedora 36, Linux, KDE

---

USB debugging activated
File transfer mode ON

My phone is recognised by my PC when attached with a wired connection. I can transfer files using KDE desktop. But ./backup.sh does not recognise the phone.

**Comment by mrrfv** [comment]
could you post the output of `adb devices` while your device is connected?

**Comment by alcukcoder** [comment]
Hi - adb devices showed no devices. So I googled around and found this:

https://stackoverflow.com/questions/21170392/android-device-does-not-show-up-in-adb-list

On Android 11, the USB preferences are in: Settings > Connected Devices > USB

Mine was MTP as default.

I changed it to PTP, allowed the necessary permissions, and got it the script to work successfully.

A question - Is it possible to have the script just download photos & files only, and not any APKs and their data?

**Comment by mrrfv** [comment]
Yes, but it requires modifying the script. All you have to do is remove or comment out the lines 210 to 226 (do not remove anything else, otherwise you could have issues with restoring the backup!):

https://github.com/mrrfv/linux-android-backup/blob/fc765bfc3f5b3ab6c1ee809248c2f611587e9f88/backup.sh#L210-L226
